version: '3.3'

services:
  app:
    image: 'myapp1'
    build:
        context: .
    container_name: app
    depends_on:
      - db
      - redis
    env_file:
      - src/main/resources/env.properties
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    env_file:
      - src/main/resources/env.properties
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"